/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.2.3).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ca.gc.ised.ndts.poc.backend.api;

import ca.gc.ised.ndts.poc.backend.api.model.Health;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-02-03T11:23:46.546156-05:00[America/Toronto]")

@Validated
@Api(value = "health", description = "the health API")
public interface HealthApi {

    default HealthApiDelegate getDelegate() {
        return new HealthApiDelegate() {};
    }

    /**
     * GET /health/ : readiness
     *
     * @return ok (status code 200)
     *         or Unexpected error (status code 200)
     */
    @ApiOperation(value = "readiness", nickname = "health", notes = "", response = Health.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "ok", response = Health.class),
        @ApiResponse(code = 200, message = "Unexpected error") })
    @RequestMapping(value = "/health/",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<Health> health() {
        return getDelegate().health();
    }

}
